# Generated by Django 2.0 on 2017-12-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171026_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Reply', verbose_name='引用'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='synonym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tag', verbose_name='关联标签'),
        ),
    ]
