# Generated by Django 2.0 on 2017-12-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171227_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pinyin',
            field=models.CharField(default='', max_length=100, verbose_name='拼音'),
            preserve_default=False,
        ),
    ]
